### ISSUE TITLE
Naming issue

### ISSUE THREAD

**Issue by TheCrazyGM** [robinvandernoord/uvx#1]
The base uv tool now has a tool-runner called uvx (which caused all kinds of issues when i just ran `uvx upgrade-all` so, might need to rethink something. I had to revert back to pipx in the mean time.
![image](https://github.com/robinvandernoord/uvx/assets/20504480/c0bb9d86-c3e7-4749-9c33-5c13e4d02db7)

**Comment by robinvandernoord** [comment]
See https://github.com/robinvandernoord/uvx2/issues/2
